### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by delucas** [nicomartin1996/TCP-EDITOR#1]
Falta la documentación esencial del proyecto:
1. Cómo lo descargo
2. Cómo lo agrego a mi _workspace_
3. Cómo lo inicio
4. Cómo lo modifico

**Comment by nicomartin1996** [comment]
No entiendo bien los puntos marcados.
Para iniciar el programa se ejecuta : 
la Clase Servidor.
la Clase "ControllPantallas".

descargar la carpeta EDITOR (El proyecto.)
esa carpeta se copia en su workSpace.

**Comment by delucas** [comment]
Todas las instrucciones deberian estar en el readme. Y deberian ser instrucciones claras.
Cerrar el issue no lo resta vigencia. Por favor, tomarse el trabajo seria y profesionalmente.

**Comment by nicomartin1996** [comment]
No se manejar github. Entienda. Pensé que tenia que cerrarlo. Ahora agrego las instrucciones al readme.

**Comment by nicomartin1996** [comment]
el punto 4. a que hace referencia ? modificar que cosa ?

**Comment by delucas** [comment]
¿Cómo se hace para contribuir al proyecto?
¿Se abre un PR? ¿Se utiliza algún método especial? ¿Se abren issues?
Es para indicar al posible colaborador cómo hacerlo :)

**Comment by nicomartin1996** [comment]
Readme actualizado. 
Confirmarme si puede cerrar este issue.
Gracias

**Comment by delucas** [comment]
El arreglo se hizo fuera de tiempo. Saludos
